'''
This script splits output files generated by AutoDock Vina, each containing multiple ligand poses, 
into separate files where each pose is saved individually. At the start, the script asks the user to enter the path to the folder 
containing the files. It processes only files in `.pdbqt` format. Each ligand pose is saved as a separate file, 
with filenames based on the original file name and the pose number. 

'''
import os

def split_complexes(input_folder):
    for filename in os.listdir(input_folder):  # read files in a folder
        if filename.endswith(".pdbqt"):  
            with open(os.path.join(input_folder, filename), 'r') as file:
                lines = file.readlines()

            models = []
            current_model = []

            for line in lines:                # extract data of each ligand pose in a file
                if line.startswith("MODEL"):
                    if current_model:
                        models.append(current_model)
                    current_model = [line]
                else:
                    current_model.append(line)

            if current_model:
                models.append(current_model)

            for i, model in enumerate(models, start=1):  # writes ligands' poses to new files
                output_filename = os.path.splitext(filename)[0] + f"_{i}.pdbqt"
                with open(os.path.join(input_folder, output_filename), 'w') as output_file:
                    output_file.writelines(model)

if __name__ == "__main__":
    folder_name = input("Enter the folder name: ")
    split_complexes(folder_name)